=== 724686158/distributedCrawler/crawler-site-manager/src/main/resources/etc/xsd/site.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://guang.org/distributedCrawler/commandlet"
	xmlns:tns="http://guang.org/distributedCrawler/commandlet"
	elementFormDefault="qualified">
	<element name="commandApp">
		<complexType>
			<sequence>
				<element name="commandlets">
					<complexType>
						<sequence>
							<element name="commandlet" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="commandlet-name" type="token" nillable="false"></element>
										<element name="commandlet-class" type="anyURI"
											nillable="false"></element>
										<element name="load-on-startup" type="boolean"
											default="false" minOccurs="0"></element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<element name="commandlet-mappings">
					<complexType>
						<sequence>
							<element name="commandlet-mapping" minOccurs="0"
								maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="commandlet-name" type="token" nillable="false"></element>
										<element name="url-pattern" type="anyURI" nillable="false"
											maxOccurs="unbounded" minOccurs="0"></element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>

			</sequence>
			<attribute name="version" default="1.0" type="double"></attribute>
		</complexType>
	</element>
</schema>

=== 724686158/distributedCrawler/target/distribute-crawler-1.0-SNAPSHOT-release/conf/site-manager/commandlet.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:commandApp version="1.0"
	xmlns:tns="http://guang.org/distributedCrawler/commandlet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://guang.org/distributedCrawler/commandlet site.xsd">
	<tns:commandlets>
		<tns:commandlet>
			<tns:commandlet-name>URLsGetter</tns:commandlet-name>
			<tns:commandlet-class>guang.crawler.siteManager.commandlet.URLsGetter</tns:commandlet-class>
			<tns:load-on-startup>false</tns:load-on-startup>
		</tns:commandlet>
		<tns:commandlet>
			<tns:commandlet-name>URLsPutter</tns:commandlet-name>
			<tns:commandlet-class>guang.crawler.siteManager.commandlet.URLsPutter</tns:commandlet-class>
			<tns:load-on-startup>false</tns:load-on-startup>
		</tns:commandlet>
		<tns:commandlet>
			<tns:commandlet-name>StatisticsGetter</tns:commandlet-name>
			<tns:commandlet-class>guang.crawler.siteManager.commandlet.StatisticsGetter</tns:commandlet-class>
			<tns:load-on-startup>false</tns:load-on-startup>
		</tns:commandlet>
		
	</tns:commandlets>
	<tns:commandlet-mappings>
		<tns:commandlet-mapping>
			<tns:commandlet-name>URLsGetter</tns:commandlet-name>
			<tns:url-pattern>/url/get</tns:url-pattern>
		</tns:commandlet-mapping>
		<tns:commandlet-mapping>
			<tns:commandlet-name>URLsPutter</tns:commandlet-name>
			<tns:url-pattern>/url/put</tns:url-pattern>
		</tns:commandlet-mapping>
		<tns:commandlet-mapping>
			<tns:commandlet-name>StatisticsGetter</tns:commandlet-name>
			<tns:url-pattern>/statistics/get</tns:url-pattern>
		</tns:commandlet-mapping>
	</tns:commandlet-mappings>



</tns:commandApp>
